encoding: utf-8

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            我乐我往
tagline:          'UTC+2 based Support Manager and Speaker'
description:      'Leone'
url:              http://blog.hileone.com

author:
  name:           'Leone'
  url:            http://weibo.com/sotsog

paginate:         25

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Leone90/leone-blog

gems:
  - jekyll-sitemap
  - jekyll-paginate
  
picture:
  source: "public/img/_original"
  output: "public/img"
  markup: "picturefill"
  presets:
    default:
      ppi: [1]
      attr:
        class: "default-img"
        itemprop: "image"
      source_large:
        media: "(min-width: 35em)"
        width: "720"
      source_medium:
        media: "(min-width: 25em)"
        width: "400"
      source_small:
        media: "(min-width: 12.5em)"
        width: "200"
      source_default:
        width: "1000"
